# Generated by Django 5.0.6 on 2024-06-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('transfer', 'Перевод на счёт')], max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
