# Generated by Django 5.0.6 on 2024-06-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payments_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_of_payment',
            field=models.DateField(auto_now_add=True),
        ),
    ]
