# Generated by Django 5.0.6 on 2024-06-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payments_date_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='link_of_payment',
            field=models.URLField(blank=True, help_text='Укажите ссылку на оплату', max_length=400, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, help_text='Укажите ID сессии', max_length=255, null=True, verbose_name='ID сессии'),
        ),
    ]
